### ISSUE TITLE
Add 'include' / 'exclude' filters to [tagcloud] shortcode [LACE]

### ISSUE THREAD

**Issue by nfreear** [IET-OU/wp-iet-generic-plugins#13]
Current crude CSS:

[@IET-OU/wp-iet-generic-plugins `../css/iet-custom-style.css` ~ line 193-195](https://github.com/IET-OU/wp-iet-generic-plugins/blob/c125f275d9f255b5d6f4e3324e3788dec9dc41f1/css/iet-custom-style.css#L193-L195):

``` css
.lace-remove-ev-tags .iet-wp-tag-cloud-plugin a[ href *= 'tag/ev-' ] {
    display: none;
}
```

Current examples:
- http://iet-lace-approval.open.ac.uk/tests-and-demos/tag-cloud-test/

```
[tagcloud format="list" x_display_count="after"]
```
## Possible extensions

Include `tag/ev-*` tags:

```
[tagcloud x_include="tag/ev-"] `
```

Exclude `tag/ev-*` tags:

```
[tagcloud x_exclude="tag/ev-"]
```
